# Generated by Django 5.1.15 on 2026-09-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('program', models.CharField(blank=True, max_length=120)),
                ('semester_section', models.CharField(blank=True, max_length=60, verbose_name='semester / section')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='students/profile/')),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='students/enrollment/')),
                ('det_score', models.FloatField(default=0.0)),
                ('model_name', models.CharField(default='buffalo_l', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
