# Generated by Django 5.1.15 on 2026-09-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_ref', models.CharField(blank=True, help_text='Tracker ID within the session.', max_length=32)),
                ('event_type', models.CharField(choices=[('looking_away', 'Looking away (prolonged)'), ('head_down', 'Head-down posture'), ('high_movement', 'High upper-body movement'), ('face_not_visible', 'Face not visible'), ('possible_drowsiness', 'Possible drowsiness (eyes closed)')], max_length=32)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0, help_text='Detector/landmark confidence for this event, 0..1.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_events', to='classes.classsession')),
                ('student', models.ForeignKey(blank=True, help_text='Null when the track was never confidently recognised.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_events', to='students.student')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['session', 'student'], name='monitoring__session_e9e834_idx'), models.Index(fields=['session', 'event_type'], name='monitoring__session_426d38_idx')],
            },
        ),
    ]
