# Generated by Django 5.2.16 on 2026-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringevent',
            name='event_type',
            field=models.CharField(choices=[('looking_away', 'Looking away (prolonged)'), ('head_down', 'Head-down posture'), ('high_movement', 'High upper-body movement'), ('face_not_visible', 'Face not visible'), ('possible_drowsiness', 'Prolonged eye closure')], max_length=32),
        ),
    ]
