# Generated by Django 5.1.15 on 2026-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_monitoringevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringevent',
            name='event_type',
            field=models.CharField(choices=[('looking_away', 'Looking away (prolonged)'), ('head_down', 'Head-down posture'), ('head_up', 'Head-up posture (chin raised)'), ('high_movement', 'High upper-body movement'), ('restless_movement', 'Restless / frequent repositioning'), ('face_not_visible', 'Face not visible'), ('left_seat', 'Prolonged absence (possibly left seat)'), ('possible_drowsiness', 'Prolonged eye closure')], max_length=32),
        ),
    ]
